language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install requests
  - pip install pymsgbox
  - pip install selenium
script: python "Creating a Python List or Tuple.py"
after_success:
  - 
